services:
  api-gateway:
    build:
      context: ../Cyber-Suite-API-Gateway
      dockerfile: Dockerfile
    container_name: cyber-suite-api-gateway
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file:
      - ./env/api-gateway/.env
    networks:
      - cyber-net

  dashboard:
    build:
      context: ../Cyber-Suite-Dashboard
      dockerfile: Dockerfile.dev
    container_name: cyber-suite-dashboard
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./env/dashboard/.env
    volumes:
      - ../Cyber-Suite-Dashboard:/app
      - /app/node_modules
    depends_on:
      - api-gateway
    networks:
      - cyber-net
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


  code-scanner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: code-scanner-ai
    restart: unless-stopped
    ports:
      - "8005:8005"
    env_file:
      - ./env/code-scanner-ai/.env
    networks:
      - cyber-net

networks:
  cyber-net:
    driver: bridge
